using System;
using System.IO;

namespace RepoTraducaoPTBR;

internal sealed class AutoTranslatorConfigurator
{
    private static readonly (string Section, string Key, string Value)[] Defaults =
    {
        ("General", "Language", "pt"),
        ("General", "FromLanguage", "en"),
        ("Files", "Directory", @"config\Translation\{Lang}\Text"),
        ("Files", "OutputFile", @"config\Translation\{Lang}\Text\_AutoGeneratedTranslations.txt"),
        ("Files", "SubstitutionFile", @"config\Translation\{Lang}\Text\_Substitutions.txt"),
        ("Files", "PreprocessorsFile", @"config\Translation\{Lang}\Text\_Preprocessors.txt"),
        ("Files", "PostprocessorsFile", @"config\Translation\{Lang}\Text\_Postprocessors.txt"),
        ("Texture", "TextureDirectory", @"config\Translation\{Lang}\Texture"),
        ("ResourceRedirector", "PreferredStoragePath", @"config\Translation\{Lang}\RedirectedResources"),
        ("Behaviour", "ReloadTranslationsOnFileChange", "True"),
    };

    private readonly IniFile _ini;
    private readonly PluginConfig _config;
    private readonly string _autoGenPath;

    public AutoTranslatorConfigurator(IniFile ini, PluginConfig config, string autoGenPath)
    {
        _ini = ini;
        _config = config;
        _autoGenPath = autoGenPath;
    }

    public void ApplyConfig()
    {
        if (AutoTranslatorBridge.IsLoaded)
        {
            if (AutoTranslatorBridge.TryApplyConfig(Defaults, out bool changed, out string? err))
            {
                if (changed)
                {
                    BceConsole.LogInfo("Config do AutoTranslator corrigida em memória (idioma/pastas pt-BR).");
                    AutoTranslatorBridge.TryReloadTranslations(out _);
                }
                return;
            }
            BceConsole.LogWarning($"Não consegui aplicar a config na memória do AutoTranslator ({err}); editando o ini (vale no próximo boot).");
        }
        foreach (var (section, key, value) in Defaults)
            _ini.Set(section, key, value);
    }

    public void ApplyEndpoint(bool announce)
    {
        string desired = _config.AutoTranslateRest.Value ? "GoogleTranslateV2" : "Passthrough";

        if (!AutoTranslatorBridge.TryGetCurrentEndpointId(out string? current))
            current = AutoTranslatorBridge.ConfiguredEndpointId;
        if (string.Equals(current, desired, StringComparison.OrdinalIgnoreCase))
            return;

        if (AutoTranslatorBridge.IsLoaded)
        {
            ClearAutoGenCache();
            AutoTranslatorBridge.TryReloadTranslations(out _);
            if (AutoTranslatorBridge.TrySetEndpoint(desired, out string? swapErr))
            {
                if (announce) BceConsole.LogInfo($"Endpoint trocado AO VIVO para {desired} — sem precisar reiniciar.");
                return;
            }
            BceConsole.LogWarning($"Troca de endpoint em runtime falhou ({swapErr}); usando o plano B (ini + restart).");
        }

        bool changed = _ini.Set("Service", "Endpoint", desired);
        if (changed && !AutoTranslatorBridge.IsLoaded)
            ClearAutoGenCache();
        if (changed && announce)
            BceConsole.LogWarning($"Endpoint de tradução definido para {desired} — REINICIE O JOGO para aplicar.");
    }

    private void ClearAutoGenCache()
    {
        try
        {
            string path = AutoTranslatorBridge.AutoTranslationsFilePath ?? _autoGenPath;
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, string.Empty);
        }
        catch (Exception ex) { BceConsole.LogWarning($"Não consegui limpar o cache de traduções: {ex.Message}"); }
    }
}
