using System.Collections.Generic;
using BepInEx.Configuration;

namespace RepoTraducaoPTBR;

internal sealed class PluginConfig
{
    private readonly Dictionary<TranslationCategory, ConfigEntry<bool>> _toggles = new();

    public ConfigEntry<bool> AutoTranslateRest { get; }
    public ConfigEntry<bool> DumpCosmetics { get; }

    public PluginConfig(ConfigFile config)
    {
        foreach (var def in TranslationCategories.All)
            _toggles[def.Id] = config.Bind("Categories", def.Key, true, def.Description);

        AutoTranslateRest = config.Bind("Automatic Translation", "Translate the Rest (Automatic)", false,
            "Machine-translates (Google) anything the dictionaries don't cover. Applies instantly. " +
            "When off, whatever is missing stays in English and is listed in _AutoGeneratedTranslations.txt.");

        DumpCosmetics = config.Bind("Tools", "Dump All Cosmetic Names", false,
            "Writes every cosmetic name currently loaded (vanilla + modded) that is MISSING from the " +
            "dictionaries to config/Translation/pt/RTLC_dump_cosmeticos.txt, ready to translate. " +
            "Use from the in-game mods menu, with all your cosmetic mods loaded.");
    }

    public IEnumerable<TranslationCategory> Categories => _toggles.Keys;

    public ConfigEntry<bool> Toggle(TranslationCategory category) => _toggles[category];

    public bool IsEnabled(TranslationCategory category) => _toggles[category].Value;
}
