using BepInEx;
using BepInEx.Configuration;
using HarmonyLib;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

namespace RepoTraducaoPTBR;

[BepInPlugin("xuaun.repo.traducao.ptbr", "REPO Tradução pt-BR", "1.0.0")]
public class Plugin : BaseUnityPlugin
{
    private const string ManagedPrefix = "RTLC_pt_";

    private static readonly (string File, string Key, string Desc)[] Categories =
    {
        ("Jogo.txt",              "Translate Game",                      "R.E.P.O.'s own menus, HUD, settings and controls (native localization + dictionary)."),
        ("Config.txt",            "Translate Mod Configs",               "Mod configuration menus (REPOConfig, CustomGrabColor, Mimic…)."),
        ("MoreHeadBridge.txt",    "Translate MoreHead Bridge",           "MoreHead Bridge interface (tabs, Customizer, Mini-Semibot…)."),
        ("CosmeticosVanilla.txt", "Translate Vanilla Cosmetics",         "Vanilla cosmetic names (they come from assetName; there is no official translation for them)."),
        ("CosmeticosXuaun.txt",   "Translate Xuaun Cosmetics",           "Cosmetic names from Xuaun mods (XuaunCosmetics, RepoPride)."),
        ("CosmeticosModded.txt",  "Translate Modded Cosmetics (Others)", "Cosmetic names from other mods (MoreHead, BASICS, etc.)."),
    };

    internal static BepInEx.Logging.ManualLogSource? Log;

    private readonly Dictionary<string, ConfigEntry<bool>> _toggles = new();
    private ConfigEntry<bool> _auto = null!;
    private ConfigEntry<bool> _dump = null!;
    private Harmony _harmony = null!;

    private void Start()
    {
        QotlCompat.Install(_harmony);
    }

    private string DictionariesDir => Path.Combine(Path.GetDirectoryName(Info.Location)!, "Dictionaries");
    private string TextDir => Path.Combine(Paths.ConfigPath, "Translation", "pt", "Text");
    private string IniPath => Path.Combine(Paths.ConfigPath, "AutoTranslatorConfig.ini");
    private string AutoGenPath => Path.Combine(TextDir, "_AutoGeneratedTranslations.txt");

    private void Awake()
    {
        Log = Logger;

        foreach (var (file, key, desc) in Categories)
        {
            var entry = Config.Bind("Categories", key, true, desc);
            entry.SettingChanged += (_, _) => SyncDictionaries(forceReload: true);
            if (file == "Jogo.txt")
                entry.SettingChanged += (_, _) => NativeLocalization.OnToggleChanged(entry.Value);
            _toggles[file] = entry;
        }

        _auto = Config.Bind("Automatic Translation", "Translate the Rest (Automatic)", false,
            "Machine-translates (Google) anything the dictionaries don't cover. Applies instantly. " +
            "When off, whatever is missing stays in English and is listed in _AutoGeneratedTranslations.txt.");
        _auto.SettingChanged += (_, _) => ApplyEndpoint(announce: true);

        _dump = Config.Bind("Tools", "Dump All Cosmetic Names", false,
            "Writes every cosmetic name currently loaded (vanilla + modded) that is MISSING from the " +
            "dictionaries to config/Translation/pt/RTLC_dump_cosmeticos.txt, ready to translate. " +
            "Use from the in-game mods menu, with all your cosmetic mods loaded.");
        _dump.SettingChanged += (_, _) => { if (_dump.Value) { DumpCosmeticNames(); _dump.Value = false; } };

        _harmony = new Harmony(Info.Metadata.GUID);
        NativeLocalization.Install(
            Path.Combine(Path.GetDirectoryName(Info.Location)!, "Localizations"),
            () => _toggles["Jogo.txt"].Value,
            _harmony);

        SyncDictionaries(forceReload: false);
        ApplyXuatConfig();
        Xuat.EnsureAutoGenFile(AutoGenPath);
        ApplyEndpoint(announce: false);
        CleanupGhostTranslationDir();
        BceConsole.LogInfo("Tradução pt-BR pronta (dicionários sincronizados).");
    }

    private void DumpCosmeticNames()
    {
        try
        {
            var type = HarmonyLib.AccessTools.TypeByName("CosmeticAsset");
            var nameField = type?.GetField("assetName");
            if (type == null || nameField == null)
            {
                BceConsole.LogWarning("CosmeticAsset não encontrado — dump cancelado.");
                return;
            }

            var names = new SortedSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var asset in UnityEngine.Resources.FindObjectsOfTypeAll(type))
            {
                if (nameField.GetValue(asset) is string n && !string.IsNullOrWhiteSpace(n))
                    names.Add(n);
            }

            var known = new HashSet<string>(StringComparer.Ordinal);
            foreach (var file in Directory.GetFiles(DictionariesDir, "*.txt"))
                foreach (var line in File.ReadAllLines(file))
                {
                    if (line.StartsWith("//") || string.IsNullOrWhiteSpace(line)) continue;
                    int eq = line.IndexOf('=');
                    if (eq > 0) known.Add(line.Substring(0, eq).Replace("\\=", "="));
                }

            var missing = names.Where(n => !known.Contains(n)).ToList();
            string outPath = Path.Combine(Paths.ConfigPath, "Translation", "pt", "RTLC_dump_cosmeticos.txt");
            Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
            File.WriteAllLines(outPath, new[]
            {
                "// Cosmetics carregados SEM tradução nos dicionários — gerado pelo botão Dump Cosmetic Names.",
                "// Preencha a parte direita e mova cada linha para o dicionário da categoria certa",
                $"// (plugins/.../Dictionaries/*.txt). Total carregado: {names.Count}; sem tradução: {missing.Count}.",
                "",
            }.Concat(missing.Select(n => $"{n}={n}")));

            BceConsole.LogInfo($"Dump de cosmetics: {names.Count} carregados, {missing.Count} sem tradução → {outPath}");
        }
        catch (Exception ex)
        {
            BceConsole.LogWarning($"Falha no dump de cosmetics: {ex.Message}");
        }
    }

    private void CleanupGhostTranslationDir()
    {
        try
        {
            string root = Path.Combine(Paths.BepInExRootPath, "Translation");
            if (!Directory.Exists(root)) return;

            string[] files = Directory.GetFiles(root, "*", SearchOption.AllDirectories);
            foreach (string f in files)
            {
                if (File.ReadAllText(f).Trim().Length > 0) return;
            }

            foreach (string f in files) File.Delete(f);
            foreach (string d in Directory.GetDirectories(root, "*", SearchOption.AllDirectories)
                                          .OrderByDescending(d => d.Length))
                Directory.Delete(d);
            Directory.Delete(root);
            BceConsole.LogDebug(@"Pasta residual BepInEx\Translation (vazia) removida.");
        }
        catch {  }
    }

    private void SyncDictionaries(bool forceReload)
    {
        bool changed = false;
        try
        {
            Directory.CreateDirectory(TextDir);
            Xuat.EnsureAutoGenFile(AutoGenPath);
            foreach (var (file, _, _) in Categories)
            {
                string src = Path.Combine(DictionariesDir, file);
                string dst = Path.Combine(TextDir, ManagedPrefix + file);
                if (_toggles[file].Value && File.Exists(src))
                {
                    string content = File.ReadAllText(src);
                    if (!File.Exists(dst) || File.ReadAllText(dst) != content)
                    {
                        File.WriteAllText(dst, content);
                        changed = true;
                    }
                }
                else if (File.Exists(dst))
                {
                    File.Delete(dst);
                    changed = true;
                }
            }

            foreach (var legacy in Categories.Select(c => c.File).Concat(new[] { "REPO_Cosmeticos.txt" }))
            {
                string p = Path.Combine(TextDir, legacy);
                if (File.Exists(p)) { File.Delete(p); changed = true; }
            }
        }
        catch (Exception ex)
        {
            BceConsole.LogWarning($"Falha ao sincronizar dicionários: {ex.Message}");
        }

        if (changed && forceReload)
        {
            if (Xuat.TryReloadTranslations(out var err))
                BceConsole.LogInfo("Dicionários recarregados ao vivo.");
            else
                BceConsole.LogDebug($"Reload ao vivo indisponível ({err}); o file-watcher do AutoTranslator aplica em ~1s.");
        }
    }

    private static readonly (string Section, string Key, string Value)[] XuatDefaults =
    {
        ("General", "Language", "pt"),
        ("General", "FromLanguage", "en"),
        ("Files", "Directory", @"config\Translation\{Lang}\Text"),
        ("Files", "OutputFile", @"config\Translation\{Lang}\Text\_AutoGeneratedTranslations.txt"),
        ("Files", "SubstitutionFile", @"config\Translation\{Lang}\Text\_Substitutions.txt"),
        ("Files", "PreprocessorsFile", @"config\Translation\{Lang}\Text\_Preprocessors.txt"),
        ("Files", "PostprocessorsFile", @"config\Translation\{Lang}\Text\_Postprocessors.txt"),
        ("Texture", "TextureDirectory", @"config\Translation\{Lang}\Texture"),
        ("ResourceRedirector", "PreferredStoragePath", @"config\Translation\{Lang}\RedirectedResources"),
        ("Behaviour", "ReloadTranslationsOnFileChange", "True"),
    };

    private void ApplyXuatConfig()
    {
        if (Xuat.IsLoaded)
        {
            if (Xuat.TryApplyConfig(XuatDefaults, out bool changed, out string? err))
            {
                if (changed)
                {
                    BceConsole.LogInfo("Config do AutoTranslator corrigida em memória (idioma/pastas pt-BR).");
                    Xuat.TryReloadTranslations(out _);
                }
                return;
            }
            BceConsole.LogWarning($"Não consegui aplicar a config na memória do AutoTranslator ({err}); editando o ini (vale no próximo boot).");
        }
        foreach (var (section, key, value) in XuatDefaults)
            SetIni(section, key, value);
    }

    private void ApplyEndpoint(bool announce)
    {
        string desired = _auto.Value ? "GoogleTranslateV2" : "Passthrough";


        if (!Xuat.TryGetCurrentEndpointId(out string? current))
            current = Xuat.ConfiguredEndpointId;
        if (string.Equals(current, desired, StringComparison.OrdinalIgnoreCase))
            return;

        bool swapped = false;
        if (Xuat.IsLoaded)
        {
            ClearAutoGenCache();
            Xuat.TryReloadTranslations(out _);
            swapped = Xuat.TrySetEndpoint(desired, out string? swapErr);
            if (swapped)
            {
                if (announce) BceConsole.LogInfo($"Endpoint trocado AO VIVO para {desired} — sem precisar reiniciar.");
                return;
            }
            BceConsole.LogWarning($"Troca de endpoint em runtime falhou ({swapErr}); usando o plano B (ini + restart).");
        }

        bool changed = SetIni("Service", "Endpoint", desired);
        if (changed && !Xuat.IsLoaded)
            ClearAutoGenCache();
        if (changed && announce)
            BceConsole.LogWarning($"Endpoint de tradução definido para {desired} — REINICIE O JOGO para aplicar.");
    }

    private void ClearAutoGenCache()
    {
        try
        {
            string path = Xuat.AutoTranslationsFilePath ?? AutoGenPath;
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, string.Empty);
        }
        catch (Exception ex) { BceConsole.LogWarning($"Não consegui limpar o cache de traduções: {ex.Message}"); }
    }

    private bool SetIni(string section, string key, string value)
    {
        try
        {
            var lines = File.Exists(IniPath)
                ? File.ReadAllLines(IniPath).ToList()
                : new List<string>();

            int sectionStart = lines.FindIndex(l => l.Trim() == $"[{section}]");
            if (sectionStart < 0)
            {
                if (lines.Count > 0 && lines[^1].Trim().Length > 0) lines.Add("");
                lines.Add($"[{section}]");
                lines.Add($"{key}={value}");
                File.WriteAllLines(IniPath, lines);
                return true;
            }

            int sectionEnd = lines.FindIndex(sectionStart + 1, l => l.TrimStart().StartsWith("["));
            if (sectionEnd < 0) sectionEnd = lines.Count;

            for (int i = sectionStart + 1; i < sectionEnd; i++)
            {
                var t = lines[i];
                int eq = t.IndexOf('=');
                if (eq <= 0 || !t.Substring(0, eq).Trim().Equals(key, StringComparison.OrdinalIgnoreCase))
                    continue;
                if (t.Substring(eq + 1).Trim() == value) return false;
                lines[i] = $"{key}={value}";
                File.WriteAllLines(IniPath, lines);
                return true;
            }

            lines.Insert(sectionEnd, $"{key}={value}");
            File.WriteAllLines(IniPath, lines);
            return true;
        }
        catch (Exception ex)
        {
            BceConsole.LogWarning($"Falha ao editar o AutoTranslatorConfig.ini ({section}.{key}): {ex.Message}");
            return false;
        }
    }
}
