using BepInEx;
using HarmonyLib;
using System.IO;

namespace RepoTraducaoPTBR;

[BepInPlugin(MyPluginInfo.PLUGIN_GUID, MyPluginInfo.PLUGIN_NAME, MyPluginInfo.PLUGIN_VERSION)]
public class Plugin : BaseUnityPlugin
{
    internal static BepInEx.Logging.ManualLogSource? Log;

    private Harmony _harmony = null!;
    private PluginConfig _config = null!;
    private DictionarySync _dictionaries = null!;
    private AutoTranslatorConfigurator _autoTranslator = null!;
    private string _dictionariesDir = null!;

    private void Awake()
    {
        Log = Logger;
        _harmony = new Harmony(Info.Metadata.GUID);

        string pluginDir = Path.GetDirectoryName(Info.Location)!;
        _dictionariesDir = Path.Combine(pluginDir, "Dictionaries");
        string textDir = Path.Combine(Paths.ConfigPath, "Translation", "pt", "Text");
        string autoGenPath = Path.Combine(textDir, "_AutoGeneratedTranslations.txt");
        string iniPath = Path.Combine(Paths.ConfigPath, "AutoTranslatorConfig.ini");

        _config = new PluginConfig(Config);
        _dictionaries = new DictionarySync(_dictionariesDir, textDir, autoGenPath, _config);
        _autoTranslator = new AutoTranslatorConfigurator(new IniFile(iniPath), _config, autoGenPath);

        WireConfigEvents();

        NativeLocalization.Install(
            Path.Combine(pluginDir, "Localizations"),
            () => _config.IsEnabled(TranslationCategory.Game),
            _harmony);
        CurrencyPatch.Install(() => _config.IsEnabled(TranslationCategory.Game), _harmony);

        _dictionaries.Sync(forceReload: false);
        _autoTranslator.ApplyConfig();
        AutoTranslatorBridge.EnsureAutoGenFile(autoGenPath);
        _autoTranslator.ApplyEndpoint(announce: false);
        GhostFolderCleanup.Run();
        BceConsole.LogInfo("Tradução pt-BR pronta (dicionários sincronizados).");
    }

    private void Start()
    {
        QotlCompat.Install(_harmony);
    }

    private void WireConfigEvents()
    {
        foreach (var category in _config.Categories)
            _config.Toggle(category).SettingChanged += (_, _) => _dictionaries.Sync(forceReload: true);

        _config.Toggle(TranslationCategory.Game).SettingChanged += (_, _) =>
            NativeLocalization.OnToggleChanged(_config.IsEnabled(TranslationCategory.Game));

        _config.AutoTranslateRest.SettingChanged += (_, _) => _autoTranslator.ApplyEndpoint(announce: true);

        _config.DumpCosmetics.SettingChanged += (_, _) =>
        {
            if (_config.DumpCosmetics.Value)
            {
                CosmeticDumper.Dump(_dictionariesDir);
                _config.DumpCosmetics.Value = false;
            }
        };
    }
}
